// Redux State String
export const FETCH_WEATHER_REQUESTED = "FETCH_WEATHER_REQUESTED";
export const FETCH_WEATHER_SUCCEEDED = "FETCH_WEATHER_SUCCEEDED";
export const FETCH_WEATHER_FAILED = "FETCH_WEATHER_FAILED";

export const FETCH_WEATHER_STATIONS = "FETCH_WEATHER_STATIONS";
export const FETCH_WEATHER_STATIONS_SUCCEEDED = "FETCH_WEATHER_STATIONS_SUCCEEDED";
export const FETCH_WEATHER_STATIONS_FAILED = "FETCH_WEATHER_STATIONS_FAILED";
export const CLEAR_WEATHER_STATIONS = "CLEAR_WEATHER_STATIONS";


// External API 
export const WEATHER_ENDPOINT = "https://api.weather.gov/";