// Redux State String
export const FETCH_WEATHER_REQUESTED = "FETCH_WEATHER_REQUESTED";
export const FETCH_WEATHER_SUCCEEDED = "FETCH_WEATHER_SUCCEEDED";
export const FETCH_WEATHER_FAILED = "FETCH_WEATHER_FAILED";

export const FETCH_WEATHER_STATION_OBSERVATIONS = "FETCH_WEATHER_STATION_OBSERVATIONS"
export const FETCH_WEATHER_STATION_OBSERVATIONS_SUCCEEDED = "FETCH_WEATHER_STATION_OBSERVATIONS_SUCCEEDED"
export const FETCH_WEATHER_STATION_OBSERVATIONS_FAILED = "FETCH_WEATHER_STATION_OBSERVATIONS_FAILED"

export const FETCH_WEATHER_STATIONS = "FETCH_WEATHER_STATIONS";
export const FETCH_WEATHER_STATIONS_FOR_ACTIVE_STATE = "FETCH_WEATHER_STATIONS_FOR_ACTIVE_STATE"
export const FETCH_WEATHER_STATIONS_SUCCEEDED = "FETCH_WEATHER_STATIONS_SUCCEEDED";
export const FETCH_WEATHER_STATIONS_FAILED = "FETCH_WEATHER_STATIONS_FAILED";
export const CLEAR_WEATHER_STATIONS = "CLEAR_WEATHER_STATIONS";
export const SET_ACTIVE_STATION = "SET_ACTIVE_STATION";
export const SET_ACTIVE_STATE = "SET_ACTIVE_STATE";


export const CALCULATE_MIN_OBSERVATIONS_SUCCEEDED = "CALCULATE_MIN_OBSERVATIONS_SUCCEEDED";
export const CALCULATE_MIN_OBSERVATIONS_FAILED = "CALCULATE_MIN_OBSERVATIONS_FAILED";
export const CALCULATE_MIN_OBSERVATIONS_REQUESTED = "CALCULATE_MIN_OBSERVATIONS_REQUESTED";

export const CALCULATE_MAX_OBSERVATIONS_SUCCEEDED = "CALCULATE_MAX_OBSERVATIONS_SUCCEEDED";
export const CALCULATE_MAX_OBSERVATIONS_FAILED = "CALCULATE_MAX_OBSERVATIONS_FAILED";
export const CALCULATE_MAX_OBSERVATIONS_REQUESTED = "CALCULATE_MAX_OBSERVATIONS_REQUESTED";

// External API 
export const WEATHER_ENDPOINT = "https://api.weather.gov/";